# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Workflow

on:
  push:
    branches:  
        main
  schedule:
    - cron: '0 * * * *'  # Execute every hour

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./github4women/github4women.csproj
    - name: Build
      run: dotnet build --no-restore ./github4women/github4women.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./github4women/github4women.csproj
    - name: Run custom script
      run: |
        chmod +x ./scripts/custom_script.sh
        ./scripts/custom_script.sh 